import { MetadataRoute } from 'next';

// ============================================================================
// ExClock Sitemap — Next.js 15 App Router
// Matches your actual app/ folder structure
// Generated: 2026-07-12
// ============================================================================

const languages = ['fr', 'es', 'de', 'it', 'ar', 'ru'];

// Static pages (no dynamic segments)
const routes = [
  { path: '', priority: 1, changeFrequency: 'weekly' as const },
  { path: '/world-clock', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/holidays', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/stopwatch', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/timer', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/alarms', priority: 0.8, changeFrequency: 'monthly' as const },
];

// Timer sub-pages: /timer/5-minute-timer, /timer/10-minute-timer, etc.
const timers = [5, 10, 15, 20, 25, 30, 45, 60];
timers.forEach((t) => {
  routes.push({ path: `/timer/${t}-minute-timer`, priority: 0.7, changeFrequency: 'monthly' as const });
});

// Legal pages: /legal/privacy, /legal/terms
const legalPages = ['privacy', 'terms'];
legalPages.forEach((slug) => {
  routes.push({ path: `/legal/${slug}`, priority: 0.4, changeFrequency: 'monthly' as const });
});

// World Clock city pages: /world-clock/{city-slug}
// Top 100 most searched cities globally
const cities = [
  'london-gb',
  'new-york-us',
  'tokyo-jp',
  'paris-fr',
  'dubai-ae',
  'singapore-sg',
  'hong-kong-hk',
  'sydney-au',
  'los-angeles-us',
  'berlin-de',
  'shanghai-cn',
  'moscow-ru',
  'rome-it',
  'madrid-es',
  'mumbai-in',
  'beijing-cn',
  'rio-de-janeiro-br',
  'cairo-eg',
  'istanbul-tr',
  'bangkok-th',
  'seoul-kr',
  'toronto-ca',
  'chicago-us',
  'san-francisco-us',
  'mexico-city-mx',
  'jakarta-id',
  'buenos-aires-ar',
  'kuala-lumpur-my',
  'sao-paulo-br',
  'delhi-in',
  'melbourne-au',
  'vancouver-ca',
  'zurich-ch',
  'amsterdam-nl',
  'vienna-at',
  'stockholm-se',
  'oslo-no',
  'copenhagen-dk',
  'helsinki-fi',
  'brussels-be',
  'prague-cz',
  'warsaw-pl',
  'budapest-hu',
  'athens-gr',
  'lisbon-pt',
  'dublin-ie',
  'edinburgh-gb',
  'manchester-gb',
  'birmingham-gb',
  'glasgow-gb',
  'cardiff-gb',
  'belfast-gb',
  'liverpool-gb',
  'leeds-gb',
  'sheffield-gb',
  'bristol-gb',
  'nottingham-gb',
  'southampton-gb',
  'leicester-gb',
  'coventry-gb',
  'brighton-gb',
  'bournemouth-gb',
  'swansea-gb',
  'newcastle-gb',
  'oxford-gb',
  'cambridge-gb',
  'york-gb',
  'bath-gb',
  'canterbury-gb',
  'exeter-gb',
  'plymouth-gb',
  'portsmouth-gb',
  'norwich-gb',
  'derby-gb',
  'stoke-gb',
  'wolverhampton-gb',
  'preston-gb',
  'blackpool-gb',
  'aberdeen-gb',
  'dundee-gb',
  'inverness-gb',
  'perth-au',
  'adelaide-au',
  'brisbane-au',
  'gold-coast-au',
  'canberra-au',
  'hobart-au',
  'darwin-au',
  'newcastle-au',
  'wollongong-au',
  'geelong-au',
  'townsville-au',
  'cairns-au',
  'toowoomba-au',
  'ballarat-au',
  'bendigo-au',
  'launceston-au',
  'mackay-au',
  'rockhampton-au',
  'bunbury-au',
  'bundaberg-au',
  'wagga-wagga-au',
  'hervey-bay-au'
];
cities.forEach((slug) => {
  routes.push({ path: `/world-clock/${slug}`, priority: 0.7, changeFrequency: 'monthly' as const });
});

// Countdown event pages: /countdown/{event-slug}
// All events from your countdown data
const countdowns = [
  'fifa-world-cup-2026',
  'fifa-world-cup-final-2026',
  'fifa-world-cup-2027',
  'fifa-womens-world-cup-2027',
  'fifa-world-cup-2028',
  'fifa-world-cup-2029',
  'fifa-world-cup-2030',
  'olympics-2026-winter',
  'olympics-2028',
  'olympics-2030-winter',
  'super-bowl-2027',
  'super-bowl-2028',
  'super-bowl-2029',
  'super-bowl-2030',
  'uefa-champions-league-final-2026',
  'uefa-champions-league-final-2027',
  'uefa-champions-league-final-2028',
  'uefa-euro-2028',
  'copa-america-2027',
  'copa-america-2029',
  'africa-cup-2027',
  'africa-cup-2029',
  'asian-cup-2027',
  'nba-finals-2026',
  'nba-finals-2027',
  'nba-finals-2028',
  'wimbledon-2026',
  'wimbledon-2027',
  'us-open-tennis-2026',
  'french-open-2026',
  'australian-open-2027',
  'formula-1-2026',
  'formula-1-2027',
  'tour-de-france-2026',
  'tour-de-france-2027',
  'cricket-world-cup-2027',
  'cricket-t20-world-cup-2026',
  'rugby-world-cup-2027',
  'rugby-world-cup-2031',
  'masters-2027',
  'boxing-day-test-2026',
  'indian-premier-league-2026',
  'indian-premier-league-2027',
  'mlb-world-series-2026',
  'nhl-stanley-cup-2026',
  'nfl-draft-2027',
  'march-madness-2027',
  'march-madness-2028',
  'kentucky-derby-2027',
  'monaco-grand-prix-2027',
  'daytona-500-2027',
  'ufc-300-anniversary',
  'wrestlemania-2027',
  'wrestlemania-2028',
  'commonwealth-games-2026',
  'pan-american-games-2027',
  'summer-universiade-2027',
  'ramadan-2026',
  'ramadan-2027',
  'ramadan-2028',
  'ramadan-2029',
  'eid-al-fitr-2026',
  'eid-al-fitr-2027',
  'eid-al-fitr-2028',
  'eid-al-fitr-2029',
  'eid-al-adha-2026',
  'eid-al-adha-2027',
  'eid-al-adha-2028',
  'eid-al-adha-2029',
  'christmas-2026',
  'christmas-2027',
  'christmas-2028',
  'christmas-2029',
  'easter-2027',
  'easter-2028',
  'easter-2029',
  'easter-2030',
  'hanukkah-2026',
  'hanukkah-2027',
  'passover-2027',
  'rosh-hashanah-2026',
  'rosh-hashanah-2027',
  'yom-kippur-2026',
  'diwali-2026',
  'diwali-2027',
  'diwali-2028',
  'holi-2027',
  'holi-2028',
  'navratri-2026',
  'navratri-2027',
  'vesak-2027',
  'chinese-new-year-2027',
  'chinese-new-year-2028',
  'chinese-new-year-2029',
  'mid-autumn-festival-2027',
  'mid-autumn-festival-2028',
  'lohri-2027',
  'maha-shivratri-2027',
  'ganesh-chaturthi-2027',
  'durga-puja-2027',
  'onam-2027',
  'pongal-2027',
  'buddha-purnima-2027',
  'guru-nanak-jayanti-2027',
  'orthodox-christmas-2027',
  'epiphany-2027',
  'assumption-of-mary-2027',
  'all-saints-day-2026',
  'all-saints-day-2027',
  'new-year-2027',
  'new-year-2028',
  'new-year-2029',
  'new-year-2030',
  'halloween-2026',
  'halloween-2027',
  'halloween-2028',
  'halloween-2029',
  'valentine-2027',
  'valentine-2028',
  'valentine-2029',
  'thanksgiving-2026',
  'thanksgiving-2027',
  'thanksgiving-2028',
  'thanksgiving-2029',
  'black-friday-2026',
  'black-friday-2027',
  'cyber-monday-2026',
  'cyber-monday-2027',
  'boxing-day-2026',
  'boxing-day-2027',
  'st-patricks-2027',
  'st-patricks-2028',
  'april-fools-2027',
  'april-fools-2028',
  'mothers-day-2027',
  'mothers-day-2028',
  'fathers-day-2027',
  'fathers-day-2028',
  'labor-day-2027-us',
  'memorial-day-2027',
  'independence-day-2027',
  'independence-day-2028',
  'cinco-de-mayo-2027',
  'juneteenth-2027',
  'veterans-day-2026',
  'veterans-day-2027',
  'presidents-day-2027',
  'mlk-day-2027',
  'earth-day-2027',
  'earth-day-2028',
  'earth-day-2029',
  'international-womens-day-2027',
  'international-womens-day-2028',
  'world-environment-day-2027',
  'pride-month-2027',
  'pride-month-2028',
  'labor-day-2028-us',
  'canada-day-2027',
  'australia-day-2027',
  'bastille-day-2027',
  'guy-fawkes-night-2026',
  'guy-fawkes-night-2027',
  'oktoberfest-2026',
  'oktoberfest-2027',
  'carnival-rio-2027',
  'carnival-rio-2028',
  'mardi-gras-2027',
  'mardi-gras-2028',
  'day-of-the-dead-2026',
  'day-of-the-dead-2027',
  'la-tomatina-2027',
  'running-of-the-bulls-2027',
  'songkran-2027',
  'songkran-2028',
  'holi-festival-2027',
  'holi-festival-2028',
  'obon-festival-2027',
  'chuseok-2027',
  'seollal-2027',
  'nowruz-2027',
  'nowruz-2028',
  'naadam-2027',
  'inti-raymi-2027',
  'dia-de-independencia-mexico-2027',
  'spring-2026',
  'summer-2026',
  'autumn-2026',
  'winter-2026',
  'spring-2027',
  'summer-2027',
  'autumn-2027',
  'winter-2027',
  'spring-2028',
  'summer-2028',
  'autumn-2028',
  'winter-2028',
  'spring-2029',
  'summer-2029',
  'autumn-2029',
  'winter-2029',
  'spring-2030',
  'summer-2030',
  'autumn-2030',
  'winter-2030'
];
countdowns.forEach((slug) => {
  routes.push({ path: `/countdown/${slug}`, priority: 0.7, changeFrequency: 'monthly' as const });
});

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.exclock.com';

  const entries: MetadataRoute.Sitemap = [];

  // Localized URLs: /fr, /fr/world-clock, /es/world-clock/london-gb, etc.
  languages.forEach((lang) => {
    routes.forEach((route) => {
      const url = route.path === '' 
        ? `${baseUrl}/${lang}` 
        : `${baseUrl}/${lang}${route.path}`;

      entries.push({
        url,
        lastModified: new Date(),
        changeFrequency: route.changeFrequency,
        priority: route.priority,
      });
    });
  });

  // Default (non-prefixed) URLs: exclock.com, exclock.com/world-clock/london-gb, etc.
  routes.forEach((route) => {
    const url = route.path === '' 
      ? baseUrl 
      : `${baseUrl}${route.path}`;

    entries.push({
      url,
      lastModified: new Date(),
      changeFrequency: route.changeFrequency,
      priority: route.priority,
    });
  });

  return entries;
}